server:
  port: 9000
spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders:
              - ContentType
              - gatewayKey