server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: room-reservation-service
          uri: http://localhost:9001
          predicates:
            - Path=/room-reservation-service/**
        - id: invoice-service
          uri: http://localhost:9002
          predicates:
            - Path=/invoice-service/**
        - id: user-service
          uri: http://localhost:9003
          predicates:
            - Path=/user-service/**