server:
  port: 9001
spring:
  jpa:
    generate-ddl: true
    show-sql: false
    open-in-view: false
    spring:
      jpa:
        database-platform: org.eclipse.persistence.platform.database.PostgreSQLPlatform
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/room-reservation-service
    username: postgres
    password: 82Ohisas

room-reservation:
  invoice-event-topic: invoice-event-topic
  reservation-event-topic: reservation-event-topic
  groupId: reservation-system-events
